# Generated by Django 5.0.7 on 2024-07-29 13:43

import Apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ramais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=50)),
                ('colaborador', models.CharField(max_length=50)),
                ('ramal', models.IntegerField()),
                ('whatsapp', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('O', 'Ocupado'), ('D', 'Disponivel')], default=Apps.models.Status, max_length=1)),
                ('time', models.DateField(auto_now=True)),
            ],
        ),
    ]
